algoritmo "semnome"
var
   n1 ,n2 :inteiro
inicio
      escreva (" Primeiro Numero ")
      leia (n1)
      escreva (" Segundo Numero ")
      leia (n2)
      se n1 > n2 entao
         escreval (" O numero 1 é maior")
      senao
           se n2 > n1 entao
              escreval (" O numero 2 é maior")
           senao
                escreval (" Os numeros são iguais ")
           fimse
      fimse
      
fimalgoritmo
