algoritmo "semnome"
var
   c ,t ,r ,t10 ,v :inteiro
inicio
      escreva (" Digite o 1° termo da PA : ")
      leia (T)
      escreva (" Qual a razao da PA : ")
      leia (R)
      escreva (" deseja repetir o termo quantas vezes ? ")
      leia (V)
      
      t10 <- (r*v)+t
      para c <- t ate t10 passo r faca
           escreval (c)
      fimpara
             escreval (" a Razao é ",r)
             escreval (" Tendo ",v," vezes o termo repetido")
      
fimalgoritmo
